### ISSUE TITLE
Installation on RPi - startup has warnings & 'please fix' about Bonjour

### ISSUE THREAD

**Issue by jroux1** [mschm/node-red-contrib-homekit#11]
Hi, installed on RPi B+ 2, with all shown instructions, including ​Install HAP-NodeJS on a Raspberry Pi, https://gist.github.com/elvisimprsntr/f23c76587d48be0ec4b9, then on ~/.node-red I installed npm install node-red-contrib-homekit, then after startup I get the errors below.

Also, the instruction to send a timestamp into the homekit node, does not return the characteristics to for instance temperature, but complains about a number been sent. 
-------------------------------------
*** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node>
*** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node&f=DNSServiceRegister>
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node>
*** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node&f=DNSServiceRegister>

**Comment by daveindustries** [comment]
Hi I'm having the same issue on startup, I'm gona have a play about with it to see if it can be resolved

**Comment by mschm** [comment]
Those Bonjour warnings are actually just _warnings_ and I have unfortunately no advise to make them disappear. Other projects I've seen that make use of [mdns](https://www.npmjs.com/package/mdns) mention these warnings and say that they should be ignored .... :/ so that's all I can propose for now. Up until now I haven't seen any issues related to that.

About the other issues that you mention – a timestamp doesn't work since the last update and you have to send an object instead, e.g. {"foo":"bar"}. I should mention that in the docs, so thanks for pointing that out :)

> Lastly, when I Reply node-RED, the node-red server falls over, and starts up again.

I don't understand what you mean by *reply* I guess you mean *deploy*? If so, could you please try a partial deploy (Modified Nodes) and tell me if Node-RED still crashes then? Thanks :)

**Comment by jroux1** [comment]
Hi Marius, by the way, brilliant idea, I would want to push through to get this to work, and thank you for replying so quickly. I have edited my initial error, and will take out the bordered server restarting out to a new issue. I will close this one when you have updated the launch page help of the bordered flow about the sending a object into the service node, rather the way it shows now on the help.

**Comment by jroux1** [comment]
Marius, just checking, in the documentation, is the below comment in your intro correct, or incorrect, i.e. should one other pass any object into the service? Because passing a timestamp does not work, or is this related to my unstable install still?

`Hint: to find out what Characteristics you can address, just send a non-object-payload (e.g. a Timestamp) and watch the debug tab ;)`

**Comment by jroux1** [comment]
I did a clean install on a new RPi3, seams okay now....

**Comment by mschm** [comment]
> Marius, just checking, in the documentation, is the below comment in your intro correct, or incorrect, i.e. should one other pass any object into the service? Because passing a timestamp does not work, or is this related to my unstable install still?

Ooops, that was wrong, sorry. It used to be the _non-object_, but it led to other issues, so now it's a _foo-object_ eg `{"foo":"bar"}`.
I corrected the docs, sorry for the confusion
