### ISSUE TITLE
negative temperature

### ISSUE THREAD

**Issue by moppi4483** [mschm/node-red-contrib-homekit#12]
Hello,

it's not possible to send a negative temperature value to the homekit-device.
I'm an European.

in the Apple Home-App I get the message that the device gets no answer.
In the Elgato Eve App i get the message that the value is lower than the minimum value.

is this an issue or I'm doing something wrong?

PS: sorry for my bad english. ;-)

**Comment by mschm** [comment]
What _Service_ is this about? Is it a _TemperatureSensor_?

**Comment by moppi4483** [comment]
It's tue temperatureSensor

**Comment by moppi4483** [comment]
Problem solved.
I found the issue.

It is an issue in HAP NodeJS. The CurrentTemperature Assesment isn't correctly configured. After editing HAPHomeKitTypes.js negative temperatures are correct in he Home-App.

**Comment by mschm** [comment]
Glad you solved it! If it's a bug in HAP NodeJS then please report to them, so it can be fixed for everyone. Thanks :)
