### ISSUE TITLE
RPi node-RED restarts with every <Deploy> of a flow.

### ISSUE THREAD

**Issue by jroux1** [mschm/node-red-contrib-homekit#13]
After installing all as per when I <deploy> node-RED after a change to the flow, the node-red server falls over, and starts up again. 

I am on RPi II B+, node version v4.2.1 and nom version 2.14.7

I first tried your instructions to install, but got similar errors. Below your instructions to install. The instructions are not clear on which directory you should be when installing these:
---------------------------
For Debian / Ubuntu you need to install the following in order to support Bonjour / Avahi

    sudo apt-get install libavahi-compat-libdnssd-dev
Then run the following command in your Node-RED user directory - typically ~/.node-red

    npm install node-red-contrib-homekit
--------------------------
Then, I tried instructions specific to RPi:

On your GitHub page: https://github.com/mschm/node-red-contrib-homekit, the HAP-NodeJS wiki has install instructions for RPi, https://github.com/KhaosT/HAP-NodeJS/wiki. This goes to a link: https://gist.github.com/elvisimprsntr/f23c76587d48be0ec4b9

In the above link, it is also not clear in which directory one should be when installing. I will try again, and ensure I am in the ~/.node-red directory, which I do not think I was in for the second attempt.
-------------------------
Thus, I suspect an installation issue of all packages to make this work on RPi, or the version of node supported by the components.
-------------------------
However, with above instructions, I was able to get iOS homekit to recognize one of the services, I used TemperatureSensor, but do not yet know what info to pass into the Service, as the instructions of passing a timestamp value into it does not give the characteristics in the Debug pane.

<Hint: to find out what Characteristics you can address, just send a non-object-payload (e.g. a Timestamp) and watch the debug tab ;) >

**Comment by iCarl** [comment]
I have the same issue with both the input payload and the restart.

**Comment by Shirk** [comment]
This might hopefully help in resolving the issue a little further:

```
22 Nov 15:52:39 - [info] Started modified flows
22 Nov 15:52:39 - [red] Uncaught Exception:
22 Nov 15:52:39 - Error: dns service error: name conflict
    at Error (native)
    at new Advertisement (/usr/lib/node_modules/node-red-contrib-homekit/node_modules/hap-nodejs/node_modules/mdns/lib/advertisement.js:56:10)
    at Object.create [as createAdvertisement] (/usr/lib/node_modules/node-red-contrib-homekit/node_modules/hap-nodejs/node_modules/mdns/lib/advertisement.js:64:10)
    at Advertiser.startAdvertising (/usr/lib/node_modules/node-red-contrib-homekit/node_modules/hap-nodejs/lib/Advertiser.js:43:30)
    at Accessory._onListening (/usr/lib/node_modules/node-red-contrib-homekit/node_modules/hap-nodejs/lib/Accessory.js:526:20)
    at emitOne (events.js:77:13)
    at HAPServer.emit (events.js:169:7)
    at HAPServer._onListening (/usr/lib/node_modules/node-red-contrib-homekit/node_modules/hap-nodejs/lib/HAPServer.js:185:8)
    at emitOne (events.js:77:13)
    at EventedHTTPServer.emit (events.js:169:7)
```

I don't get crashes at each deploy but I managed to reproduce it after a few tries while having Node started on the commandline.

**Comment by jroux1** [comment]
Did a clean install of RPi, and node-red, then 
sudo apt-get install libavahi-compat-libdnssd-dev
npm install node-red-contrib-homekit, 
seams to work now, will monitor....
