### ISSUE TITLE
Lightbulbs = 'No Response', others works

### ISSUE THREAD

**Issue by jroux1** [mschm/node-red-contrib-homekit#14]
Hi, I rebuilt a new RPi this weekend, and only added node-red, with the homekit contrib. Got all working to read temp & humidity, and get 3 lights represented on Homekit. Did this by linking up mqtt as inputs to the homekit service. But, after about two hours of the config, the lightbulbs will show 'No Response' on the iOS Homekit screen, and have no functionality on that screen. However, all seams to be working on Node-Red side. By switching the light on and off through another button to the mqtt channel, the light switches off / on, and on the node-red with the Homekit, one can see when it goes on, or off. Any ideas where to look, or is some code enhancement required?

![fullsizeoutput_bed](https://cloud.githubusercontent.com/assets/16258123/20651158/2da7d4c6-b4e8-11e6-8bcf-064bc7d76bb5.jpeg)

**Comment by mschm** [comment]
Hi,
would you mind sharing some part of your setup?
1. select only the homekit nodes in your flow
2. in the menu chose Export -> Clipboard
3. copy and paste the JSON here (modify "pinCode" entries!)

That would help a lot, thanks

**Comment by jroux1** [comment]
[{"id":"b673519b.6c10f","type":"mqtt in","z":"15cca89e.084e27","name":"Stoep Light","topic":"sensors/espeasy/ESP70/Light/Switch","qos":"2","broker":"44599b0a.f9806c","x":81.5,"y":89,"wires":[["fd5bb18d.39297"]]},{"id":"3aa0445b.ee7dbc","type":"mqtt out","z":"15cca89e.084e27","name":"Stoep Light","topic":"sensors/espeasy/ESP70/gpio/12","qos":"","retain":"","broker":"44599b0a.f9806c","x":693.5,"y":86,"wires":[]},{"id":"fd5bb18d.39297","type":"function","z":"15cca89e.084e27","name":"hk-i","func":"\nmsg.payload = { \"On\" : msg.payload } ;\nreturn msg;","outputs":1,"noerr":0,"x":222.5,"y":88,"wires":[["ada46a09.f05768"]]},{"id":"b6051b93.c8d85","type":"function","z":"15cca89e.084e27","name":"hk-o","func":"varX = msg.payload ; \nmsg.payload = varX.On ;\nreturn msg;","outputs":1,"noerr":0,"x":528,"y":85,"wires":[["3aa0445b.ee7dbc"]]},{"id":"36b9d801.f4a588","type":"mqtt in","z":"15cca89e.084e27","name":"HQuad Light","topic":"sensors/espeasy/ESP71/Light/Switch","qos":"2","broker":"44599b0a.f9806c","x":81,"y":148,"wires":[["877f2829.db72f8"]]},{"id":"b3252c0f.04944","type":"mqtt out","z":"15cca89e.084e27","name":"HQuad Light","topic":"sensors/espeasy/ESP71/gpio/12","qos":"","retain":"","broker":"44599b0a.f9806c","x":695,"y":141,"wires":[]},{"id":"3d913a55.a4430e","type":"function","z":"15cca89e.084e27","name":"hk-o","func":"varX = msg.payload ; \nmsg.payload = varX.On ;\nreturn msg;","outputs":1,"noerr":0,"x":533,"y":141,"wires":[["b3252c0f.04944"]]},{"id":"877f2829.db72f8","type":"function","z":"15cca89e.084e27","name":"hk-i","func":"\nmsg.payload = { \"On\" : msg.payload } ;\nreturn msg;","outputs":1,"noerr":0,"x":226,"y":145,"wires":[["8f4e8e26.c4ba68"]]},{"id":"cba47b21.e5ba1","type":"homekit-service","z":"15cca89e.084e27","accessory":"37a693c5.7d523c","name":"Temp","serviceName":"TemperatureSensor","x":387.5,"y":277,"wires":[[]]},{"id":"495cec5e.f6383c","type":"mqtt in","z":"15cca89e.084e27","name":"Quad Temp","topic":"sensors/espeasy/ESP62/Air/Temperature","qos":"2","broker":"44599b0a.f9806c","x":85,"y":279,"wires":[["ac75a407.d0a7c8"]]},{"id":"ac75a407.d0a7c8","type":"function","z":"15cca89e.084e27","name":"hk-i","func":"\nvarX = parseFloat(msg.payload) ;\nmsg.payload = { \"CurrentTemperature\" : varX} ;\nreturn msg;","outputs":1,"noerr":0,"x":238.5,"y":278,"wires":[["cba47b21.e5ba1"]]},{"id":"efd9defd.df024","type":"homekit-service","z":"15cca89e.084e27","accessory":"860d796e.4416f","name":"Hum","serviceName":"HumiditySensor","x":388.5,"y":326,"wires":[[]]},{"id":"14d6fe32.3c8daa","type":"mqtt in","z":"15cca89e.084e27","name":"Quad Hum","topic":"sensors/espeasy/ESP62/Air/Humidity","qos":"2","broker":"44599b0a.f9806c","x":75,"y":327,"wires":[["db519e3.6af7d6"]]},{"id":"db519e3.6af7d6","type":"function","z":"15cca89e.084e27","name":"hk-i","func":"\nvarX = parseFloat(msg.payload) ;\nmsg.payload = {\"CurrentRelativeHumidity\" : varX} ;\nreturn msg;","outputs":1,"noerr":0,"x":238,"y":327,"wires":[["efd9defd.df024"]]},{"id":"4a7a939.78299ec","type":"homekit-service","z":"15cca89e.084e27","accessory":"670412f5.39ab34","name":"Lux","serviceName":"LightSensor","x":389.5,"y":382,"wires":[[]]},{"id":"5392108.0d99cf","type":"mqtt in","z":"15cca89e.084e27","name":"Roof Lux","topic":"sensors/espeasy/ESP63/Light/Lux","qos":"2","broker":"44599b0a.f9806c","x":76,"y":383,"wires":[["388cce33.fb42ba"]]},{"id":"388cce33.fb42ba","type":"function","z":"15cca89e.084e27","name":"hk-i","func":"\nvarX = parseInt(msg.payload) ;\nmsg.payload = {\"CurrentAmbientLightLevel\" : varX} ;\nreturn msg;","outputs":1,"noerr":0,"x":235,"y":383,"wires":[["4a7a939.78299ec"]]},{"id":"8f4e8e26.c4ba68","type":"homekit-service","z":"15cca89e.084e27","accessory":"252ba2e1.7a325e","name":"Quad2Light","serviceName":"Lightbulb","x":374.5,"y":145,"wires":[["3d913a55.a4430e"]]},{"id":"ada46a09.f05768","type":"homekit-service","z":"15cca89e.084e27","accessory":"ddb47a2c.138578","name":"StoepLight","serviceName":"Lightbulb","x":382.5,"y":91,"wires":[["b6051b93.c8d85"]]},{"id":"ec1d3de.d5d554","type":"function","z":"15cca89e.084e27","name":"hk-o","func":"varX = msg.payload ; \nmsg.payload = varX.On ;\nreturn msg;","outputs":1,"noerr":0,"x":522,"y":205,"wires":[["7517be81.79f438"]]},{"id":"7517be81.79f438","type":"mqtt out","z":"15cca89e.084e27","name":"Kitchen Light","topic":"sensors/espeasy/ESP72/gpio/12","qos":"","retain":"","broker":"44599b0a.f9806c","x":687.5,"y":206,"wires":[]},{"id":"9ab9f614.aa0be8","type":"function","z":"15cca89e.084e27","name":"hk-i","func":"\nmsg.payload = { \"On\" : msg.payload } ;\nreturn msg;","outputs":1,"noerr":0,"x":224,"y":208,"wires":[["1a3bc92.f8ccfb7"]]},{"id":"64f0f9ff.298a6","type":"mqtt in","z":"15cca89e.084e27","name":"Kitchen Light","topic":"sensors/espeasy/ESP72/Light/Switch","qos":"2","broker":"44599b0a.f9806c","x":83,"y":209,"wires":[["9ab9f614.aa0be8"]]},{"id":"1a3bc92.f8ccfb7","type":"homekit-service","z":"15cca89e.084e27","accessory":"c7314b2.c199838","name":"QuadLight","serviceName":"Lightbulb","x":371.5,"y":208,"wires":[["ec1d3de.d5d554"]]},{"id":"7f2bdc8a.7c9354","type":"function","z":"15cca89e.084e27","name":"Test","func":"\nmsg.payload = { \"Test\" : 2 } ;\nreturn msg;","outputs":1,"noerr":0,"x":381,"y":33,"wires":[[]]},{"id":"a5ceffa4.c1a5e","type":"inject","z":"15cca89e.084e27","name":"","topic":"","payload":"","payloadType":"date","repeat":"","crontab":"","once":false,"x":199.5,"y":33,"wires":[["7f2bdc8a.7c9354"]]},{"id":"44599b0a.f9806c","type":"mqtt-broker","z":"","broker":"192.168.2.11","port":"1883","clientid":"","usetls":false,"compatmode":true,"keepalive":"60","cleansession":true,"willTopic":"","willQos":"0","willRetain":"false","willPayload":"","birthTopic":"","birthQos":"0","birthRetain":"false","birthPayload":""},{"id":"37a693c5.7d523c","type":"homekit-accessory","z":"","accessoryName":"QuadTemp","pinCode":"111-11-111","port":"","manufacturer":"Shenzhen Rhino Technology Co","model":"DHT22","serialNo":"Default Serial Number"},{"id":"860d796e.4416f","type":"homekit-accessory","z":"","accessoryName":"Quad.Humidity","pinCode":"111-11-111","port":"","manufacturer":"Shenzhen Rhino Technology Co","model":"DHT22","serialNo":"1115"},{"id":"670412f5.39ab34","type":"homekit-accessory","z":"","accessoryName":"Roof.Lux","pinCode":"111-11-111","port":"","manufacturer":"Adafruit","model":"TSL2561","serialNo":"1116"},{"id":"252ba2e1.7a325e","type":"homekit-accessory","z":"","accessoryName":"Quad2OutsideLight","pinCode":"111-11-111","port":"","manufacturer":"Itead","model":"Sonoff","serialNo":"505092"},{"id":"ddb47a2c.138578","type":"homekit-accessory","z":"","accessoryName":"StoepLight","pinCode":"111-11-111","port":"","manufacturer":"Itead","model":"Sonoff","serialNo":"502222"},{"id":"c7314b2.c199838","type":"homekit-accessory","z":"","accessoryName":"QuadOutsideLight","pinCode":"111-11-111","port":"","manufacturer":"Itead","model":"Sonoff","serialNo":"488845"}]

**Comment by mschm** [comment]
In the meantime, did you observe the problem any further? Any more hints you can give on this? I am having a hard time reproducing. 
There is an issue with the flow lifecycle, so if your problem occurs after redeploying, that would probably lead to that. Apart from that I really don't see anything at the moment...

**Comment by mschm** [comment]
I am closing this. If the issue remains, please reopen.

**Comment by S474N** [comment]
> In the meantime, did you observe the problem any further? Any more hints you can give on this? I am having a hard time reproducing.
> There is an issue with the flow lifecycle, so if your problem occurs after redeploying, that would probably lead to that. Apart from that I really don't see anything at the moment...

Have problem with "re-deploy". Is there way to fix it? There is "No response" on devices and I must deleted them and add again.
