### ISSUE TITLE
Favorites and caching 

### ISSUE THREAD

**Issue by maragelis** [mschm/node-red-contrib-homekit#15]
Hi first up good job. 

I am having an issue where after a reboot of the node all HomeKit devices show up as new devices. 

Let me get into some detail. 
Say you have a lamp in a bedroom. If you mark this lamp as not favorite so it doesn't show on home page, and also add this lamp to a scene. After a node reboot the lamp will show up on home page and will also not be active in the scene. The room it was in is saved. 

Thanks for your response, keep up the good work.

**Comment by hanselb** [comment]
Hi guys,

I tested the code on this pull request  https://github.com/mschm/node-red-contrib-homekit/pull/25 and it seems to resolve this issue. Tested on my RPi2 by just replacing the Homekit.js file in /usr/lib/node_modules/node-red-contrib-homekit/homekit.js and it works perfectly. 😄

**Comment by maragelis** [comment]
Sadly after a few tries the #25 is a hit and miss

**Comment by mschm** [comment]
I hope this is fixed in version 0.2.1. In case the problem persists, please reopen this issue.
