### ISSUE TITLE
Unable to send value to homekit-service

### ISSUE THREAD

**Issue by LeonSerri** [mschm/node-red-contrib-homekit#16]
Hi, 

I have successfully installed the home kit-service in node-red following the instruction specified in the README. Unfortunately, I haven't find the way format the value in order to visualise it in the home kit app. I have also tried to give, at homekit-service,  a random value as input. The error in the debug is "Invalid payload type: number".

Could you please give me any further information to correctly test the homekit-service?

Thank you so much for your help.

Leonardo

**Comment by mschm** [comment]
apologies, the info was outdated. this is correct:

<p><strong>Hint</strong>: to find out what <em>Characteristics</em> you can address, just send <code>{&quot;foo&quot;:&quot;bar&quot;}</code> and watch the debug tab ;)</p>

Hope it helps!

**Comment by tonivss** [comment]
How can I send it?

Thanks
