### ISSUE TITLE
Light Dimmer

### ISSUE THREAD

**Issue by stelioskat** [mschm/node-red-contrib-homekit#18]
Hi,

Thanks a lot for your effort! I currently cannot find a service for dimming lights functionality.
I only see the Lightbulb option which has an on/off function but not an adjustable brightness. Is it not supported yet? 

Thanks in advance

**Comment by ukmoose** [comment]
I missed it to start with see https://github.com/mschm/node-red-contrib-homekit/issues/3 for what you need to do

**Comment by mschm** [comment]
@stelioskat need any more assistance with this?

**Comment by stelioskat** [comment]
@mschm @ukmoose the workaround worked perfectly! Thank you.
