### ISSUE TITLE
Behind Firewall

### ISSUE THREAD

**Issue by ram1505** [mschm/node-red-contrib-homekit#2]
Which port should I open to allow home kit to work? I'm behind firewall using UFW.

**Comment by mschm** [comment]
As far as I understand, the underlying https://github.com/KhaosT/HAP-NodeJS does not assign specific ports. Instead, random free ports are allocated by the system, so there is no static port-range to open in your fw. 
Configuring a specific port from the node config dialog will be supported in the future, but until it's there you may want to check if https://github.com/nfarina/homebridge has any suggestions for firewall usage and adopt their strategy. 
Hopefully that helps.

**Comment by ram1505** [comment]
Sure. Thanks. I'll update here if I find any alternative ways.

**Comment by mschm** [comment]
You can now specify ports for accessories

**Comment by ram1505** [comment]
Awesome! Will try it out and feedback.

**Comment by ram1505** [comment]
Works perfectly now. Thanks a lot @mschm
