### ISSUE TITLE
Scenes disappear after restarting node-red

### ISSUE THREAD

**Issue by aditanase** [mschm/node-red-contrib-homekit#21]
Every time I restart the node-red service, all the scenes that I have defined in iOS (e.g. Good Night) are removed.

The accessories appear as unreachable for a short time (as expected) but when they come back the scenes disappear.

**Comment by mschm** [comment]
Disappearing scenes... pretty much as in https://github.com/mschm/node-red-contrib-homekit/issues/15

**Comment by hanselb** [comment]
Hi guys,

I tested the code on this pull request  https://github.com/mschm/node-red-contrib-homekit/pull/25 and it seems to resolve this issue. Tested on my RPi2 by just replacing the Homekit.js file in /usr/lib/node_modules/node-red-contrib-homekit/homekit.js and it works perfectly. 😄

**Comment by iOlli** [comment]
@hanselb: It is possible the homekit.js have different locations? I find the file on my PI in /home/node_modules/node-red-contrib-homekit/homekit.js
But the this work around and it doesn't works.

**Comment by mschm** [comment]
@aditanase v0.2.1 should have resolved this issue

**Comment by aditanase** [comment]
I confirm that it works now.

**Comment by jonathanschneider** [comment]
It seems like the error is back. Every time I deploy a change in Node-RED, my scenes disappear and the devices are added back to favourites. I have v0.2.1 installed and the Node-RED version is v0.17.5.

**Comment by salas81** [comment]
I'm still having this problem. Every time I restart node-red I have to re-pair all the accessories. Any word on this?

**Comment by jonathanschneider** [comment]
@salas81 no, I suggest you migrate to [node-red-contrib-homekit-bridged](https://www.npmjs.com/package/node-red-contrib-homekit-bridged)
