### ISSUE TITLE
Basic help is needed

### ISSUE THREAD

**Issue by iCarl** [mschm/node-red-contrib-homekit#28]
I'm a complete noob when it comes to this.
If I would like the payload of {"on":1} to be changed to "on" and {"on":0} to be changed to "off" in order for my MQTT relays to change state.
How do I do this? I don' understand how to write functions.

**Comment by timhodson** [comment]
You could use something like this to change the output from the homekit node. Simply paste this into a function node and wire it up between a homekit node and some other node.

```javascript
if (msg.payload.On == 1)
{
    msg.payload = "ON"
}else{
    msg.payload = "OFF"
}
return msg;
```
![image](https://cloud.githubusercontent.com/assets/554539/22023205/226d6150-dcbd-11e6-9bd9-571c98d3f1c1.png)

Hope that helps :)

**Comment by iCarl** [comment]
Thank you so much! Somehow managed to get it to work by improvising, but your function is waaay cleaner!
<img width="834" alt="skarmavbild 2017-01-17 kl 17 41 09" src="https://cloud.githubusercontent.com/assets/4193514/22029925/570ee4f0-dcdc-11e6-8b48-eb9ec47bc7f1.png">
