### ISSUE TITLE
Missing characteristics (feature?)

### ISSUE THREAD

**Issue by tedstriker** [mschm/node-red-contrib-homekit#3]
Hello,
upfront: great job you did there!

For some reason a lightbulb doesn't accept properties like brightness or color.
But adding them as default might not be the best idea, as this changes appearance and behavior in the iOS UI.
Maybe it's possible to add checkboxes in the items node to enable optional characteristics.

I'm curious what you think about it.

**Comment by mschm** [comment]
**Brightness**, **Hue** and **Saturation** are optional Characteristics of a lightbulb. The reason they weren't accepted was a bug in my implementation ;) sorry for that. A fix is in progress...

I like the idea of making characteristics selectable in the configuration dialog. But for now please stick with this solution: 
**Before** adding the device in the iOS Home App, send a message containing optional characteristics to be activated like so ```{"Brightness":80, "Hue":223, "Saturation":50}```
After that the lightbulb will be recognized with the desired features... does that work for you?

**Comment by tedstriker** [comment]
This work's very well.
Thank you.

**Comment by mschm** [comment]
Thanks for your feedback

**Comment by jonathanschneider** [comment]
Is it correct that I need to run this workaround every time I deploy a change? How is the fix coming along?

**Comment by hubshi** [comment]
Can you please post a sample flow for this workaround?

**Comment by jonathanschneider** [comment]
There are two inject nodes: one for dimmable lamps and one for dimmable and colorful lamps. You obviously only need one of them.

```
[
    {
        "id": "336afcd7.abfcdc",
        "type": "inject",
        "z": "8ddaab3f.a55468",
        "name": "MakeDimmable",
        "topic": "",
        "payload": "{\"Brightness\":80}",
        "payloadType": "json",
        "repeat": "",
        "crontab": "",
        "once": true,
        "x": 280,
        "y": 60,
        "wires": [
            [
                "3a4df8ca.bc3978"
            ]
        ]
    },
    {
        "id": "c8037418.ba5d",
        "type": "inject",
        "z": "8ddaab3f.a55468",
        "name": "MakeColourful",
        "topic": "",
        "payload": "{\"Brightness\":80,\"Hue\":223,\"Saturation\":50}",
        "payloadType": "json",
        "repeat": "",
        "crontab": "",
        "once": true,
        "x": 280,
        "y": 100,
        "wires": [
            [
                "3a4df8ca.bc3978"
            ]
        ]
    },
    {
        "id": "3a4df8ca.bc3978",
        "type": "homekit-service",
        "z": "8ddaab3f.a55468",
        "accessory": "c54bd643.dba81",
        "name": "Lamp",
        "serviceName": "Lightbulb",
        "x": 470,
        "y": 80,
        "wires": [
            []
        ]
    },
    {
        "id": "c54bd643.dba81",
        "type": "homekit-accessory",
        "z": "",
        "accessoryName": "Lamp",
        "pinCode": "111-11-111",
        "port": "",
        "manufacturer": "Default Manufacturer",
        "model": "Default Model",
        "serialNo": "Default Serial Number",
        "accessoryType": "1"
    }
]
```

**Comment by zbot473** [comment]
@jonathanschneider So I need to repair every deploy, correct?

**Comment by jonathanschneider** [comment]
@zbot473 no, the inject nodes I posted are triggered every time Node-RED starts. Once imported and connected to your HomeKit nodes, you won’t have to do anything.
