### ISSUE TITLE
Accessories caching problems with two iPhones

### ISSUE THREAD

**Issue by mpolazzo** [mschm/node-red-contrib-homekit#30]
Hi, I have successfully deployed this on a Raspberry Pi as main CPU, then I have created my home on HomeKit, on my iPhone. After that I decided to add my wife's iPhone in the HomeKit environment.
The problem comes when I add new devices, even just for testing and then I remove them. They are correctly removed on my iPhone, but not on my wife's. So she has a lot of non existing devices. 
Might it be a caching issue on my Raspberry Pi ?
Could you please double check the process flow in this scenario ?
Thanks, great job.
Marco

**Comment by mschm** [comment]
The underlying library hap-nodejs states in its readme:
>Hint: the Homekit Application Protocol (HAP) allows that you can pair a Homekit device with one device. As soon as the Homekit device is paired, its not possible to pair with another iOS device anymore.

Therefore I am afraid, that it is not possible to pair with more than one device.
