### ISSUE TITLE
How are homekit update requests handled?

### ISSUE THREAD

**Issue by zieherf** [mschm/node-red-contrib-homekit#31]
At the moment I don't see any output messages generated when homekit services request updates for characteristic values (e.g. a TemperatureSensor requests a new value for CurrentTemperature). It this something that is planned for implementation?

**Comment by mschm** [comment]
The intended usage right now does not follow a request-response pattern. Instead, you should "feed" the node with updates whenever they occur. That's particularly comfortable in a publish-subscribe world, e.g. when your temperature sensor communicates via mqtt. Value updates are also being propagated to the paired device, so I haven't actually seen a need for polling, as you describe. 
So it is not planned for implementation right now. If you want to add more more detail to your usecase, please feel free to reopen this issue :)
