### ISSUE TITLE
No device list after installation

### ISSUE THREAD

**Issue by tsmt** [mschm/node-red-contrib-homekit#4]
Hi

I nearly successfully installed the node. After install the node appears in the interface. But i can't use it because there is no device list. When I reload the interface on :1880, the node disappears permanently from the interface.

I tried to reinstall it, restart the nodered service, reboot the raspberry pi. Everytime I can just see the node within no reload cycles of the webinterface. So this is reproducable.

Can i provide any error log?

Versions:
NodeJS v4.6.2
NPM 2.15.11
Node-Red 0.15.2

on Raspbian Jessie

regards,
Tobi

**Comment by mschm** [comment]
It seems that the node dependencies aren't installed completely. What's does it say when you do `npm install` inside the node-red-contrib-homekit folder? Any errors?

**Comment by tsmt** [comment]
Thank you but no, sorry. There is no error output on `npm install`

```
[ts@rhea] ~/.node-red/node_modules/node-red-contrib-homekit npm install
[ts@rhea] ~/.node-red/node_modules/node-red-contrib-homekit 
```

in npm_modules is a hap-nodejs module. That seems to be the only dependency. 

Is there any other way I can debug this? (Sorry - I'm more the device programming guy than frontend, so I'm not very familiar with nodejs tools)

**Comment by mschm** [comment]
what does it say when you do
```
cd node_modules/hap-nodejs
npm install
```

**Comment by mschm** [comment]
@tsmt is this still an issue or were you able to resolve it?

**Comment by tsmt** [comment]
Oh sorry, I'm not at home at the moment. I will try to fix it next weekend.

**Comment by mschm** [comment]
If it's still an issue, feel free to reopen it

**Comment by MohammadAhmad1990** [comment]
I am not able to add accessory on my iphone I am already running homebridge on another machine. here is my error. Kindly help

root@nodered:~/.node-red/node_modules/node-red-contrib-homekit# npm install
loadDep:hap-nodejs → 304  ▄ ╢██████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
WARN engine hap-nodejs@0.4.24: wanted: {"node":">=4.3.2"} (current: {"node":"4.2npm ERR! Linux 4.4.0-72-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2

npm ERR! Cannot read property 'target' of null
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /root/.node-red/node_modules/node-red-contrib-homekit/npm-debug.log
root@nodered:~/.node-red/node_modules/node-red-contrib-homekit#
