### ISSUE TITLE
Invalid property. Try one of these: Name, On, Brightness, Hue, Saturation, Name

### ISSUE THREAD

**Issue by ukmoose** [mschm/node-red-contrib-homekit#6]
Loving the node!   

Trying to follow the advice in issue #3 by sending a switch node a message. 
 so for example.

`msg.payload = {"Brightness":80};`

whatever I try I get the following error message for a light called "Reading Light"

12 Nov 15:49:23 - [warn] [homekit-service:Reading Light] Invalid property.
Try one of these: Name, On, Brightness, Hue, Saturation, Name

(also Name appears in the list twice) ;-)

many thanks

Mark

**Comment by jclement** [comment]
I ran into this too. 

In homekit.js there is a check on the msg.payload to verify it's an object (in the "input" event handler):

```js
if (!(msg.payload instanceof Object)) {
```

For some reason, if I use a inject block to generate a JSON payload, it works fine.  However, when I use a function block to return a payload it fails that check.  But... if I change that check to the following, everything works fine.

```js
if (!((typeof msg.payload) === 'object')) {
```

So it's an "object".  It's just not an instance of "Object".  My Javascript-foo is insufficient to explain how this is even possible...

**Comment by mschm** [comment]
Thanks for the great effort! Should be fixed now.
