### ISSUE TITLE
Error on Install: error     node-gyp rebuild

### ISSUE THREAD

**Issue by alport** [mschm/node-red-contrib-homekit#62]
Hi - can you help? 
Getting an error on install: 
Thanks,

1782 info postuninstall node-red-contrib-homekit@0.2.1
1783 error mdns@2.3.4 install: `node-gyp rebuild`
1783 error Exit status 1
1784 error Failed at the mdns@2.3.4 install script.
1784 error This is most likely a problem with the mdns package,
1784 error not with npm itself.
1784 error Tell the author that this fails on your system:
1784 error     node-gyp rebuild
1784 error You can get their info via:
1784 error     npm owner ls mdns
1784 error There is likely additional logging output above.
1785 error System Linux 4.9.59-v7+
1786 error command "/usr/bin/nodejs" "/usr/bin/npm" "install" "node-red-contrib-homekit"
1787 error cwd /home/pi/.node-red
1788 error node -v v4.8.2
1789 error npm -v 1.4.21
1790 error code ELIFECYCLE
1791 verbose exit [ 1, true ]

**Comment by piejanssens** [comment]
Did you do `sudo apt-get install libavahi-compat-libdnssd-dev` before installing node-red-contrib-homekit as stated in the readme?

**Comment by alport** [comment]
That fixed it - thanks.
