### ISSUE TITLE
no service choice

### ISSUE THREAD

**Issue by Clemzo** [mschm/node-red-contrib-homekit#68]
Hi, I use Node-Red on RPI and I've just to install node-red-contrib-homekit.
But when I want used my firts homekit node, in Service list there is no choice possible.
Is there any thing else to install ?

Thank's

**Comment by Clemzo** [comment]
Ok more informations :
At start node-red says :
```
5 Jan 14:14:01 - [warn] [homekit] Error: Could not locate the bindings file. Tried:
 → /home/pi/.node-red/node_modules/ed25519/build/ed25519.node
 → /home/pi/.node-red/node_modules/ed25519/build/Debug/ed25519.node
 → /home/pi/.node-red/node_modules/ed25519/build/Release/ed25519.node
 → /home/pi/.node-red/node_modules/ed25519/out/Debug/ed25519.node
 → /home/pi/.node-red/node_modules/ed25519/Debug/ed25519.node
 → /home/pi/.node-red/node_modules/ed25519/out/Release/ed25519.node
 → /home/pi/.node-red/node_modules/ed25519/Release/ed25519.node
 → /home/pi/.node-red/node_modules/ed25519/build/default/ed25519.node
 → /home/pi/.node-red/node_modules/ed25519/compiled/6.12.3/linux/arm/ed25519.node
```
Is it possible to repair it with out re-install ?

Thank's

**Comment by profesionalTI** [comment]
Try to install by console with help of this web:
https://www.npmjs.com/package/node-red-contrib-homekit



Coordialmente,
Best Regards,

Marcelo A. Anuch Medina
Consultor de Empresas Público/Privadas
Ingeniero Comercial, MBA UDD
Business Management


🔒   La información contenida en esta transmisión es confidencial y está dirigida exclusivamente a el o los destinatarios indicados. Cualquier uso por otras personas que no sean sus destinatarios está sancionado por la ley chilena. Si ha recibido esta transmisión por error, por favor destrúyala y notifique al remitente si corresponde. Las opiniones expresadas en este correo son las de su autor y pueden no ser compartidas por la compañía. Marcelo A. Anuch Medina,  no asume obligaciones ni responsabilidades por el contenido de este correo. Tampoco garantiza que la transmisión de este correo sea segura o libre de errores, y en consecuencia, no responde por virus, pérdidas, destrucción, recepción tardía o incompleta.

🍀  Antes de imprimir este correo electrónico asegúrese que sea realmente necesario: Cuidemos el medio ambiente! Todos vivimos en un solo planeta.

**Comment by Clemzo** [comment]
Thank you very much.

I've uninstalled libavahi and contrib-homekit and re installed and now all works fine

thank's again
