### ISSUE TITLE
Temperature and Humidity Sensor

### ISSUE THREAD

**Issue by webfrank** [mschm/node-red-contrib-homekit#7]
Hi, I cannot send Temperature and Humidity value to HomeKit. I have a flow which retrieves those values from MQTT and creates two separate objects:
{ CurrentTemperature: xx } and { CurrentRelativeHumidity: xx }
and sends them to two different nodes HomeKit of type TemperatureSensor and HumiditySensor. I found those devices with my iPad but I have a no reply error and no value displayed.

**Comment by mschm** [comment]
Hi, could you please try that again with the updated version? Beware: breaking changes. Thanks :)

**Comment by webfrank** [comment]
Hi, installed new version but same result. This is what I'm sending but on iPad I got no reply for each.
![schermata 2016-11-14 alle 19 33 01](https://cloud.githubusercontent.com/assets/4688664/20277536/42f7f118-aaa1-11e6-97e7-f912724e955b.png)

**Comment by webfrank** [comment]
Hi, I finally managed to get it working. On issue was mine as I was sending values like strings and not float. Another issue is the in the code there is no .on('get') handler and HomeKit App sends a get once and if i does not got a reply marks the device as not reachable. I put this code and it seems to work but I think should be handled better:

...
var allCharacteristics = service.characteristics.concat(service.optionalCharacteristics)
    allCharacteristics.map(function (characteristic, index) {
      var cKey = characteristic.displayName.replace(/ /g, '')
      if (characteristic.props.perms.indexOf('pw') > -1) {
        supported.read.push(cKey)
      }
      if ((characteristic.props.perms.indexOf('pr') + characteristic.props.perms.indexOf('ev')) > -2) {
        supported.write.push(cKey)
      }
      **characteristic.on('get', function(cb) { cb() })**
    })
...

**Comment by webfrank** [comment]
Please look at this code, I think it could be ok:

------
`// which characteristics are supported?
    var supported = { read: [], write: []}
    var cachedValues = {}

    var allCharacteristics = service.characteristics.concat(service.optionalCharacteristics)
    allCharacteristics.map(function (characteristic, index) {
      var cKey = characteristic.displayName.replace(/ /g, '')
      if (characteristic.props.perms.indexOf('pw') > -1) {
        supported.read.push(cKey)
      }
      if ((characteristic.props.perms.indexOf('pr') + characteristic.props.perms.indexOf('ev')) > -2) {
        supported.write.push(cKey)
      }
      characteristic.on('get', function(cb) {
        var key = this.displayName.replace(/ /g, '')
        if(cachedValues[key]) {
          cb(null, cachedValues[key])
        } else {
          cb()
        }
      })
    })
`
------
`// respond to inputs
    this.on('input', function (msg) {
      if (msg.hasOwnProperty('payload')) {
        // payload must be an object
        var type = typeof msg.payload
        if (type != 'object') {
          node.warn('Invalid payload type: ' + type)
          return
        }
      } else {
        node.warn('Invalid message (payload missing)')
        return
      }

      // iterate over characteristics to be written
      Object.keys(msg.payload).map(function (key, index) {
        if (supported.write.indexOf(key) < 0) {
          // characteristic is not supported
          node.warn('Characteristic ' + key + ' cannot be written.\nTry one of these: ' + supported.write.join(', '))
        } else {
          service.setCharacteristic(Characteristic[key], msg.payload[key])
          cachedValues[key] = msg.payload[key]
        }
      })
    })
`

**Comment by iCarl** [comment]
@webfrank Mind sharing your setup?

**Comment by webfrank** [comment]
This is a typical flow with sensors and home kit:

`[
    {
        "id": "9b57f463.8247f",
        "type": "mqtt in",
        "z": "e5f7f519.795298",
        "name": "",
        "topic": "TAVERNA/humidity",
        "qos": "0",
        "broker": "1c96b4d9.51fd9b",
        "x": 134.5,
        "y": 93,
        "wires": [
            [
                "5d4f21f0.22217",
                "a4a074db.d6b238",
                "6bed28d5.d54528",
                "757f782b.c84988",
                "c3757ef1.5aa66"
            ]
        ]
    },
    {
        "id": "492a2737.611b78",
        "type": "mqtt in",
        "z": "e5f7f519.795298",
        "name": "",
        "topic": "TAVERNA/temperature",
        "qos": "0",
        "broker": "1c96b4d9.51fd9b",
        "x": 138,
        "y": 300,
        "wires": [
            [
                "71a5a715.ef297",
                "5108dadf.2f554c",
                "1d1b626b.eccff6",
                "6774651e.a6f714",
                "c3757ef1.5aa66"
            ]
        ]
    },
    {
        "id": "5108dadf.2f554c",
        "type": "ui_chart",
        "z": "e5f7f519.795298",
        "name": "Temp Chart",
        "group": "1619356c.715f7b",
        "order": 2,
        "width": 0,
        "height": 0,
        "label": "",
        "chartType": "line",
        "legend": "false",
        "xformat": "%H:%M",
        "interpolate": "basis",
        "nodata": "",
        "ymin": "",
        "ymax": "",
        "removeOlder": 1,
        "removeOlderUnit": "86400",
        "x": 399.5,
        "y": 351,
        "wires": [
            [],
            []
        ]
    },
    {
        "id": "71a5a715.ef297",
        "type": "ui_gauge",
        "z": "e5f7f519.795298",
        "name": "Temp Gauge",
        "group": "1619356c.715f7b",
        "order": 1,
        "width": 0,
        "height": 0,
        "gtype": "gage",
        "title": "",
        "label": "°C",
        "format": "{{value}}",
        "min": 0,
        "max": "40",
        "colors": [
            "#00B500",
            "#E6E600",
            "#CA3838"
        ],
        "x": 399.5,
        "y": 269,
        "wires": []
    },
    {
        "id": "5d4f21f0.22217",
        "type": "ui_gauge",
        "z": "e5f7f519.795298",
        "name": "Hum Gauge",
        "group": "7421ead3.d20b5c",
        "order": 1,
        "width": 0,
        "height": 0,
        "gtype": "gage",
        "title": "",
        "label": "%",
        "format": "{{value}}",
        "min": 0,
        "max": "100",
        "colors": [
            "#00B500",
            "#E6E600",
            "#CA3838"
        ],
        "x": 396,
        "y": 69,
        "wires": []
    },
    {
        "id": "a4a074db.d6b238",
        "type": "ui_chart",
        "z": "e5f7f519.795298",
        "name": "Hum Chart",
        "group": "7421ead3.d20b5c",
        "order": 2,
        "width": 0,
        "height": 0,
        "label": "",
        "chartType": "line",
        "legend": "false",
        "xformat": "%H:%M",
        "interpolate": "basis",
        "nodata": "",
        "ymin": "",
        "ymax": "",
        "removeOlder": 1,
        "removeOlderUnit": "86400",
        "x": 396,
        "y": 142,
        "wires": [
            [],
            []
        ]
    },
    {
        "id": "8e0b61ad.947098",
        "type": "homekit-service",
        "z": "e5f7f519.795298",
        "accessory": "7b87ef12.2ddaf8",
        "name": "Temperatura",
        "serviceName": "TemperatureSensor",
        "x": 734.5,
        "y": 314,
        "wires": [
            [
                "c3757ef1.5aa66"
            ]
        ]
    },
    {
        "id": "1d1b626b.eccff6",
        "type": "function",
        "z": "e5f7f519.795298",
        "name": "",
        "func": "msg.payload = {\n    CurrentTemperature: parseFloat(msg.payload)\n};\nreturn msg;",
        "outputs": 1,
        "noerr": 0,
        "x": 560.5,
        "y": 312,
        "wires": [
            [
                "8e0b61ad.947098"
            ]
        ]
    },
    {
        "id": "c3757ef1.5aa66",
        "type": "debug",
        "z": "e5f7f519.795298",
        "name": "",
        "active": false,
        "console": "false",
        "complete": "false",
        "x": 955.5,
        "y": 205,
        "wires": []
    },
    {
        "id": "6bed28d5.d54528",
        "type": "function",
        "z": "e5f7f519.795298",
        "name": "",
        "func": "msg.payload = {\n    CurrentRelativeHumidity: parseFloat(msg.payload)\n};\nreturn msg;",
        "outputs": 1,
        "noerr": 0,
        "x": 571,
        "y": 107,
        "wires": [
            [
                "12aa1527.c3b20b"
            ]
        ]
    },
    {
        "id": "12aa1527.c3b20b",
        "type": "homekit-service",
        "z": "e5f7f519.795298",
        "accessory": "7b87ef12.2ddaf8",
        "name": "Umidità",
        "serviceName": "HumiditySensor",
        "x": 727,
        "y": 106,
        "wires": [
            [
                "c3757ef1.5aa66"
            ]
        ]
    },
    {
        "id": "6774651e.a6f714",
        "type": "ThingspeakSendSimple",
        "z": "e5f7f519.795298",
        "name": "Temperatura Taverna",
        "writekey": "*****",
        "fieldid": "1",
        "x": 203.5,
        "y": 403,
        "wires": []
    },
    {
        "id": "757f782b.c84988",
        "type": "ThingspeakSendSimple",
        "z": "e5f7f519.795298",
        "name": "Umidità Taverna",
        "writekey": "******",
        "fieldid": "2",
        "x": 170.5,
        "y": 193,
        "wires": []
    },
    {
        "id": "1c96b4d9.51fd9b",
        "type": "mqtt-broker",
        "z": "",
        "broker": "localhost",
        "port": "1883",
        "clientid": "",
        "usetls": false,
        "compatmode": false,
        "keepalive": "60",
        "cleansession": true,
        "willTopic": "",
        "willQos": "0",
        "willRetain": "false",
        "willPayload": "",
        "birthTopic": "",
        "birthQos": "0",
        "birthRetain": "false",
        "birthPayload": ""
    },
    {
        "id": "1619356c.715f7b",
        "type": "ui_group",
        "z": "",
        "name": "Temperatura",
        "tab": "9c8ba475.1a4c7",
        "order": 1,
        "disp": true,
        "width": "6"
    },
    {
        "id": "7421ead3.d20b5c",
        "type": "ui_group",
        "z": "",
        "name": "Umidità",
        "tab": "9c8ba475.1a4c7",
        "order": 2,
        "disp": true,
        "width": "6"
    },
    {
        "id": "7b87ef12.2ddaf8",
        "type": "homekit-accessory",
        "z": "",
        "accessoryName": "Taverna",
        "pinCode": "111-11-111",
        "port": "",
        "manufacturer": "Bizmate",
        "model": "ESPEasy",
        "serialNo": "0000"
    },
    {
        "id": "9c8ba475.1a4c7",
        "type": "ui_tab",
        "z": "",
        "name": "Taverna",
        "icon": "dashboard",
        "order": 4
    }
]`

**Comment by mschm** [comment]
I wasn't able to connect to the broker, so I synthesized the payload (just a number as string). The following flow works for me. 

```
[{"id":"f18e6883.a72e78","type":"debug","z":"9f2fd2c1.5ad08","name":"","active":true,"console":"false","complete":"false","x":570,"y":100,"wires":[]},{"id":"75320394.90131c","type":"function","z":"9f2fd2c1.5ad08","name":"","func":"msg.payload = {\n CurrentRelativeHumidity: parseFloat(msg.payload)\n};\nreturn msg;","outputs":1,"noerr":0,"x":290,"y":100,"wires":[["c5235d7b.9abcf"]]},{"id":"c5235d7b.9abcf","type":"homekit-service","z":"9f2fd2c1.5ad08","accessory":"5de7ec63.007334","name":"Umidità","serviceName":"HumiditySensor","x":420,"y":100,"wires":[["f18e6883.a72e78"]]},{"id":"b6602dc5.d1fc9","type":"inject","z":"9f2fd2c1.5ad08","name":"","topic":"","payload":"70.3","payloadType":"str","repeat":"","crontab":"","once":false,"x":170,"y":100,"wires":[["75320394.90131c"]]},{"id":"5de7ec63.007334","type":"homekit-accessory","z":"","accessoryName":"Taverna","pinCode":"111-11-111","port":"","manufacturer":"Bizmate","model":"ESPEasy","serialNo":"0000"}]
```
If it works for you, you need to examine the output from your mqtt node. have you tried using a _JSON_-Node to parse the mqtt output to an actual node object before you pass it into the function node?

**Comment by mschm** [comment]
Assuming that this issue is solved, I am closing it.
