### ISSUE TITLE
Help: Contact Sensor Errors

### ISSUE THREAD

**Issue by brianhanifin** [mschm/node-red-contrib-homekit#78]
I'm trying to setup a Window Contact Sensor. I can connect it to Homekit, and I the debug object is showing the 1's and 0's I'm sending it. But the Homekit object is throwing the following error.

`"Invalid payload type: string"`

So I used a Node-red function to convert the string to an integer.

    str = msg.payload;
    msg.payload = parseInt(str);
    return msg;

But that also throws an error.

`Invalid payload type: number`

I setup the Accessory as a "SENSOR" and the the Service as a "ContactSensor". What am I doing wrong?

**Comment by maragelis** [comment]
so Service "Contact Sensor" has a  Characteristic.ContactSensorState what you have to do is send a payload with the following Characteristic. 

{
ContactSensorState:"1"
}


or 

msg.payload.ContactSensorState="1"

**Comment by brianhanifin** [comment]
That's what I was missing. Thank you so much!

**Comment by Clubsport** [comment]
What was the solution to this...? 

I'm also dealing with the conversion for Homebridge, and tried:

var x = msg.payload 
var y = Number(x);
msg.payload.Brightness="${y}" 
return msg;

But getting again the string error message......
Any help would be appreciated! 👍
