### ISSUE TITLE
GarageDoorOpener remains with "opening" message

### ISSUE THREAD

**Issue by alasso** [mschm/node-red-contrib-homekit#83]
Hi,

I have an installation on raspberry pi and I created a homekit node to open a garage door by calling a URL (http://192.162.XX/accionar). 

On iOS appears the device and, when I press it, it shows a message "opening", but never ends o change.

Does anyone happened something like this?

Adrian

**Comment by profesionalTI** [comment]
Hola, mira, lo mismo me paso con una chapa tradicional eléctrica, lo que hice fue que apenas se habrio, envié un mensaje falso a homekit cambiando un estado. Tienes que bajar el manual de apple para homekit https://nube.recursosti.cl/index.php/s/Tra3kVjHExuPPgf


Coordialmente,
Best Regards,

Marcelo A. Anuch Medina
Consultor de Empresas Público/Privadas
Ingeniero Comercial, MBA UDD
Business Management


🔒   La información contenida en esta transmisión es confidencial y está dirigida exclusivamente a el o los destinatarios indicados. Cualquier uso por otras personas que no sean sus destinatarios está sancionado por la ley chilena. Si ha recibido esta transmisión por error, por favor destrúyala y notifique al remitente si corresponde. Las opiniones expresadas en este correo son las de su autor y pueden no ser compartidas por la compañía. Marcelo A. Anuch Medina,  no asume obligaciones ni responsabilidades por el contenido de este correo. Tampoco garantiza que la transmisión de este correo sea segura o libre de errores, y en consecuencia, no responde por virus, pérdidas, destrucción, recepción tardía o incompleta.

🍀  Antes de imprimir este correo electrónico asegúrese que sea realmente necesario: Cuidemos el medio ambiente! Todos vivimos en un solo planeta.

**Comment by alasso** [comment]
Gracias Marcelo!
Solucionado. Lo había intentando en el pasado pero se vé que no lo hice bien. Ahora use un nodo "function" para setear msg.payload.TargetDoorState = 0 (cerrado) y funciona correctamente.

Muchas gracias nuevamente,
Adrian

**Comment by profesionalTI** [comment]
Excelente Adrian, me alegro mucho, que otras cosas tienes con Homekit?

**Comment by alasso** [comment]
Con homekit recién estoy empezando porque no podía hacer funcionar el porton de garage que era mi principal necesidad.
Tengo otras cosas funcionando con Amazon Alexa con dos Echo Dots y dos Echo Spot que los uso para encender una lampara, encender un monitor. Para estoy estoy utilizando:
1) Sonoff Smart Switch Basic:  http://sonoff.itead.cc/en/products/sonoff/sonoff-basic
2) Broadlink RM Mini 3: http://www.ibroadlink.com/rmMini3/

Saludos,
Adrian
