### ISSUE TITLE
Please, i would love further documentation

### ISSUE THREAD

**Issue by iCarl** [mschm/node-red-contrib-homekit#9]
Please do a well documented wiki-section, this node is great

**Comment by mschm** [comment]
Do you have any specific topics in mind? Why would you prefer a Wiki over the Readme? I chose the Readme for documentation because it is contained in the repo; centralized, easier to maintain and most important: displayed outside of github such as on npmjs and Node-RED flow library.

**Comment by iCarl** [comment]
Just some kind of documentation would be nice.
I can't get any payload output from homekit nodes, and I dont know why input doesn't get read by my MQTT inputs

**Comment by mschm** [comment]
For now, maybe these two example flows might help you: [Switch Example](https://flows.nodered.org/flow/c32cf0a0f6f556ba62aa726815369059) and [Garage Example](https://flows.nodered.org/flow/c32cf0a0f6f556ba62aa726815369059) 

Let me know how if it helps :)
